---
extends: default

rules:
  document-start: disable
  line-length:
    max: 150
    level: warning
  truthy:
    check-keys: false
ignore:
  # ignore helm charts (using differing linter for helm)
  - templates/
  - docusaurus
