labels:
  Environment: dev
  cluster: use1-rdev
  datacenter: use1-rdev.k8s.adgear.com
  alerting: nopage

replicaCount: 2

service:
  type: ClusterIP
  port: 8080
  appPort: 8085
  kafkaPort: 8087

image:
  tag: "0.0.2"

kafkafetcherimage:
  repository: adgear-docker.jfrog.io/adgear/go-commons-kafka-fetcher
  tag: v0.0.5

ingress:
  enabled: false
  class: nginx
  annotations:
    adgear.com/Environment: dev
  hosts:
    - host: "rtb-bidder-dev.k8s.adgear.com"
      paths: ["/"]
  tls:
    - hosts:
        - "rtb-bidder-dev.use1-rdev.k8s.adgear.com"
        - "rtb-bidder-dev.k8s.adgear.com"
      secretName: "rtb-bidder-dev-tls"

environment_vars:
  ENVIRONMENT: "dev"

monitoring:
  enabled: true

vmprobe:
  enabled: true
  api_url: "https://rtb-bidder-dev.k8s.adgear.com/health/readiness"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

logging:
  enabled: false
