---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "service.fullname" . }}-secret
  labels:
    {{- include "service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.vault }}
  {{ $key }}:  {{ $value | b64enc | quote }}
  {{- end }}
