{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  endpoints:
  {{- range .Values.serviceMonitor.targets }}
  - interval: {{ .interval }}
    scrapeTimeout: {{ .scrapeTimeout }}
    targetPort: {{ .port }}
    path: {{ .path }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
{{- end }}
