name: build-push-docker

on:
  workflow_call:
    outputs:
      artifactory_hostname:
        description: "Jfrog docker repo hostname"
        value: ${{ jobs.get-secrets.outputs.artifactory_hostname }}
      artifactory_username:
        description: "Jfrog docker repo password"
        value: ${{ jobs.get-secrets.outputs.artifactory_username }}
      artifactory_password:
        description: "Jfrog docker repo password"
        value: ${{ jobs.get-secrets.outputs.artifactory_password }}

jobs:
  get-secrets:
    name: Get vault secrets
    runs-on: [self-hosted, ubuntu-22.04-medium]
    permissions:
      id-token: write   # permissions required by hashicorp/vault-action (request JWT token)
      contents: read

    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.3
        with:
          method: jwt                               # leave as is
          path: adgear-github-actions               # leave as is (dedicated vault role for github actions)
          url: https://vault.int.adgear.com:8200    # leave as is (production vault instance)
          secrets:
            |
            secret/ep/shared/artifactory/username value | ARTIFACTORY_USERNAME ;
            secret/ep/shared/artifactory/password value | ARTIFACTORY_PASSWORD ;
            secret/ep/shared/artifactory/docker_hostname value | ARTIFACTORY_HOSTNAME ;

      - name: output env vars
        id: secrets
        run:
          |
          echo "::add-mask::$ARTIFACTORY_USERNAME"
          echo "::add-mask::$ARTIFACTORY_PASSWORD"
          echo "::add-mask::$ARTIFACTORY_HOSTNAME"
          echo "artifactory_username=${ARTIFACTORY_USERNAME}" >> $GITHUB_OUTPUT
          echo "artifactory_password=${ARTIFACTORY_PASSWORD}" >> $GITHUB_OUTPUT
          echo "artifactory_hostname=${ARTIFACTORY_HOSTNAME}" >> $GITHUB_OUTPUT

    outputs:
      artifactory_username: ${{ steps.secrets.outputs.artifactory_username }}
      artifactory_password: ${{ steps.secrets.outputs.artifactory_password }}
      artifactory_hostname: ${{ steps.secrets.outputs.artifactory_hostname }}
